name: php-8

on:
  workflow_dispatch:
    inputs:
      PHP_VER:
        description: 'php Version'
        required: true
        default: '8.2.8'

env:
  REGISTRY: gitea.v1.zhaoxiaodan.com
  PHP_VER: ${{ inputs.PHP_VER }}

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04
      volumes:
        - /run/user/1000/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: pangliang
          password: ${{ secrets.ACCESS_TOKEN_PACKAGE_RW }}

      - name: Build and push ${{ env.PHP_VER }}-fpm-alpine
        uses: docker/build-push-action@v5
        with:
          context: php/
          push: true
          tags: gitea.v1.zhaoxiaodan.com/pangliang/php:${{ env.PHP_VER }}-fpm-alpine
          file: php/Dockerfile-8-fpm-alpine
          build-args: PHP_VER=${{ env.PHP_VER }}
      
      - name: Build and push ${{ env.PHP_VER }}-cli-alpine
        uses: docker/build-push-action@v5
        with:
          context: php/
          push: true
          tags: gitea.v1.zhaoxiaodan.com/pangliang/php:${{ env.PHP_VER }}-cli-alpine
          file: php/Dockerfile-8-cli-alpine
          build-args: PHP_VER=${{ env.PHP_VER }}


