FROM pangliang/ubuntu
MAINTAINER pangliang "418094911@qq.com"

#php5-fpm
RUN apt-get install -y php5-fpm php5-cli php5-curl php5-json php5-mcrypt




COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf


