FROM php:7.4-cli-alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
	&& apk update \
        && apk add freetype-dev\
		libwebp-dev\
		libxpm-dev\
		libpng-dev\
		libjpeg-turbo-dev\
		libzip-dev\
	&& docker-php-ext-install mysqli pdo_mysql gd zip

