FROM php:5.6-fpm-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
	&& apk update \
        && apk add freetype-dev\
		libwebp-dev\
		libxpm-dev\
		libpng-dev\
		libjpeg-turbo-dev\
		libzip-dev\
	&& docker-php-ext-configure gd \
	    --with-gd \
	    --with-webp-dir \
	    --with-jpeg-dir \
	    --with-png-dir \
	    --with-zlib-dir \
	    --with-xpm-dir \
	    --with-freetype-dir \
	&& docker-php-ext-install mysqli pdo_mysql gd zip
