FROM php:7.3-fpm-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
	&& apk update \
        && apk add freetype-dev\
		libpng-dev\
		libjpeg-turbo-dev\
		libzip-dev\
	&& docker-php-ext-configure gd \
	    --with-gd \
	    --with-webp-dir \
	    --with-jpeg-dir \
	    --with-png-dir \
	    --with-zlib-dir \
	    --with-xpm-dir \
	    --with-freetype-dir \
	    --enable-gd-native-ttf
	&& docker-php-ext-install mysqli pdo_mysql gd zip
